### ISSUE TITLE
Win miner -> submitting share but no payout

### ISSUE THREAD

**Issue by mrprobz** [gramcoinorg/mining-pool#4]
Hi Ilia, 
While running the last grampool miner on windows. its submitting shares but not receiving any payout. Do you also manage the pool side?

**Comment by iliachesnokov** [comment]
The distribution logic of shares is as follows: if, during the period between the miners receiving the job and the pool receiving the profit (after the transaction is sent), you have submitted your shares, you will receive a portion of the profit with a multiplier of YOUR_SHARES / TOTAL_SHARES (for that period). In other words, it's a fair payment for your device's work.

It appears that the shares generated by your device either did not meet the criteria of the giver or were sent but did not receive a payout.
